//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSeguro.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMSeguro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMSeguro()
        {
            this.TRAfiliacions = new HashSet<TRAfiliacion>();
        }
    
        public int Id { get; set; }
        public int Compania { get; set; }
        public string Numero { get; set; }
        public int Tipo { get; set; }
        public string Descripcion { get; set; }
        public int FactorImpuesto { get; set; }
        public int PorcentajeComision { get; set; }
        public int Prima { get; set; }
        public int Moneda { get; set; }
        public int EdadMaxima { get; set; }
        public System.DateTime FechaVigencia { get; set; }
        public int ImporteMensual { get; set; }
        public int Cobertura { get; set; }
        public int Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual TMCompaniaAseguradora TMCompaniaAseguradora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAfiliacion> TRAfiliacions { get; set; }
    }
}
